### ISSUE TITLE
Select location on planned meal

### ISSUE THREAD

**Issue by LeonorLunatech** [lunatech-labs/lunatech-lunch-planner#100]
# Description
The user should be able to select for a given date only one scheduled meal if there are planning to go to any of the available locations.
For that goal a new column should be added, Location, which shows where it's scheduled.
Also, for UI consistency sake the user should still see a checkbox for the selection, but with the caveat that would only be possible to select only one location per date (this validation should happen on the frontend as well as in the backend).

**On why use a checkbox and not a radio button**: Certainly a radio button would make things easier on selection, validation wise, since you would be allowed to select only one option. But this has two drawbacks:
- When there is planed meal for only one location (this is going to be unlikely in the future) a radio button doesn't make sense.
- On the scenario where you want to erase your selection, for example when you're on holidays but mistakenly selected a date. For which we need other solutions.

# Users
Everyone

# Depends
On #99

**Comment by arnieel** [comment]
During testing, I noticed that there is already a validation for selecting more than one Meal Schedule of the same day (please see screenshot)

<img width="366" alt="screen shot 2017-09-15 at 09 31 55" src="https://user-images.githubusercontent.com/11879980/30471823-66559766-99fa-11e7-93a3-4e86a3d97373.png">

I believe this is already enough to prevent users from selecting more than one schedule of different locations. What do you think?

**Comment by LeonorLunatech** [comment]
Yes, that looks like to serve the purpose :)

Kind regards,

Leonor Boga
Software developer

+31 10 750 26 00
leonor.boga@lunatech.com
http://www.lunatech.com <http://lunatech.com/>
