### ISSUE TITLE
Multiple attendance 

### ISSUE THREAD

**Issue by Shermans2806** [lunatech-labs/lunatech-lunch-planner#191]
In the monthly report for October, Aleksandar Gjorgjevich is noted in all: RTD, AMS and not-attending. He  can only be in 1 place at a time.

**Comment by Shermans2806** [comment]
In the same report Jasper, Leonor, Maria, Willem-Jan are noted twice for the same location on the same day

**Comment by wjglerum** [comment]
Last week I had the problem where I didn't appear in any report at all, because my profile was missing.

**Comment by LeonorLunatech** [comment]
These are two completely different bugs. The bug with Alex is very weird, the other one I think I have a proper fix

**Comment by LeonorLunatech** [comment]
Both issues where fixed.
Alex issue was fixed directly in the DB and the issue with the other users had a better fix.
None of the issue were reproducible so they may happen again in the future
