### ISSUE TITLE
Deleted schedules are being considered by the Lunch bot

### ISSUE THREAD

**Issue by leonorboga** [lunatech-labs/lunatech-lunch-planner#225]
Lunch in Rotterdam for the 20th of Dec has been removed, but lunch bot still shows the option

<img width="702" alt="Screenshot 2019-12-17 at 11 01 47" src="https://user-images.githubusercontent.com/12009309/70985668-c5a3ac80-20bc-11ea-9c11-f7fb1006a80d.png">

**Comment by LeonorLunatech** [comment]
Fixed on #234
