### ISSUE TITLE
Monthly reports

### ISSUE THREAD

**Issue by Shermans2806** [lunatech-labs/lunatech-lunch-planner#88]
I would really appreciate a monthly report with the total amount of people who have had lunch. This is for tax purposes.

**Comment by Shermans2806** [comment]
I will also need a list of names of everyone eating (this is so that it can be double checked)

**Comment by LeonorLunatech** [comment]
Export to excel

**Comment by iPlessmann** [comment]
Shelley needs this feature by the end of the month, she needs a report containing the name of the person that have eaten, the days in which that person ate, per location when available. At the end there should be a count of the people that ate and that didnt.

**Comment by pepite** [comment]
I think this will never work. What is needed is to register people *after *they took the meal. This is for financial purpose. This cannot be based on something people plan to do. We need a different issue than that one.

**Comment by LeonorLunatech** [comment]
I will close this ticket and open new ones for new monthly report requirements
