### ISSUE TITLE
Default lunch-option

### ISSUE THREAD

**Issue by haribageski** [lunatech-labs/lunatech-lunch-planner#94]
It would be nice to have an option to have some lunch option selected by default.
For example the option for which there were the most votes.
And only not to get lunch if you select option ‘no lunch’.

**Comment by LeonorLunatech** [comment]
But how do you imagine this in practice? We cannot have the app deciding for people.
And it would mean to build a component that would gather and analise statistics...

**Comment by haribageski** [comment]
I meant something else. It's very practical to select the dates interval in which you are at work on Fridays, and if you forget to select a meal for the upcoming Friday but the day is within the range you have selected for being at work, then it would be logical the application to add one extra meal to the option that was selected most times from the options of that week (no historical data or statistical analysis). So it's not that the app is deciding for people in this way :) 
What do you think?

**Comment by Shermans2806** [comment]
I do not understand what you mean Hari. Could you please explain this to me?

**Comment by haribageski** [comment]
For example suppose one enters that he\she is working in Rotterdam from date X to date Y and suppose he\she doesn't select a meal for some date Z that is between the dates X and Y. Then there still should be a lunch for that person.

**Comment by Shermans2806** [comment]
ah ok, but then there should be a reminder to fill it in. I think there is another issue saying that filling in yes/no should be mandatory.

**Comment by haribageski** [comment]
Or to automatically get what is served for the day (the aplication to adjust the counting).
