### ISSUE TITLE
Allow people to explicitly say that they are not attending a meal

### ISSUE THREAD

**Issue by LeonorLunatech** [lunatech-labs/lunatech-lunch-planner#95]
Add an extra option to allow people to explicitly say that they are not attending a meal.

**Comment by arnieel** [comment]
I've been thinking about this. 

Maybe we could make use of Slack API to post private messages once a day to users who have not decided yet. And for convenience, maybe users can respond (with just a click) to Slack bot directly so they won't have to go to the web app.
This way, we can track who will attend, who will not, and who didn't respond. Also less hassle to users.

What do you think?
